const products = [
  {
    _id: "1",
    name: "Intel i3 CPU",
    image: "/images/cpu.jpg",
    description:
      'It is one of three types of processors in the "i" series (also called the Intel Core family of processors). The Core i3 processor is available in multiple speeds, ranging from 1.30 GHz up to 3.50 GHz, and features either 3 MB or 4 MB of cache. It utilizes either the LGA 1150 or LGA 1155 socket on a motherboard',
    brand: "Intel",
    category: "CPU",
    price: "Rs 75000",
    countInStock: "5",
    rating: "5",
    numReviews: "10",
  },
  {
    _id: "2",
    name: "Intel i7 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 125000",
    countInStock: "2",
    rating: "2.5",
    numReviews: "4",
  },
  {
    _id: "3",
    name: "Intel i3 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 75000",
    countInStock: "5",
    rating: "1.5",
    numReviews: "10",
  },
  {
    _id: "4",
    name: "Intel i3 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 75000",
    countInStock: "5",
    rating: "5",
    numReviews: "10",
  },
  {
    _id: "5",
    name: "Intel i3 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 75000",
    countInStock: "5",
    rating: "4.5",
    numReviews: "10",
  },
];
export default products;
