const products = [
  {
    _id: 1,
    name: "Intel i3 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 75000",
    countInStock: "5",
    rating: "5",
    numReviews: "10",
  },
  {
    _id: 2,
    name: "Intel i7 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 125000",
    countInStock: "2",
    rating: "4",
    numReviews: "4",
  },
  {
    _id: 3,
    name: "Intel i3 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 75000",
    countInStock: "5",
    rating: "5",
    numReviews: "10",
  },
  {
    _id: 4,
    name: "Intel i3 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 75000",
    countInStock: "5",
    rating: "5",
    numReviews: "10",
  },
  {
    _id: 5,
    name: "Intel i3 CPU",
    image: "/images/cpu.jpg",
    description: "Intel high performance gaming CPU",
    brand: "Intel",
    category: "CPU",
    price: "Rs 75000",
    countInStock: "5",
    rating: "5",
    numReviews: "10",
  },
];
export default products;
